/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirline;

import Business.Airliner;
import Business.Flight;
import Business.TravelAgency;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author HP
 */
public class ViewFlightDetailsJPanel extends javax.swing.JPanel {
    
    private JPanel cardSequenceJPanel;
    private TravelAgency travelAgency;
    private Flight flight;

    /**
     * Creates new form ViewFlightDetailsJPanel
     */
    ViewFlightDetailsJPanel(JPanel cardSequenceJPanel, Flight flight,TravelAgency travelAgency ) {
        initComponents();
        this.cardSequenceJPanel = cardSequenceJPanel;
        this.flight = flight;
        this.travelAgency = travelAgency;
        populateFlightDetails();        
    }
    
    private void populateFlightDetails(){
        comboBoxAirliner.removeAllItems();
        comboBoxAirliner.addItem(flight.getAirlinerName());
        txtArrivalTime.setText(flight.getArrivalTime());
        txtDepartureTime.setText(flight.getDepartureTime());
        txtAvailableSeats.setText(String.valueOf(flight.getAvailableSeats()));
        txtFlightNo.setText(flight.getFlightNumber());
        txtDestination.setText(flight.getDestination());
        txtSeats.setText(String.valueOf(flight.getSeat()));
        txtSource.setText(flight.getSource());
        txtPrice.setText(String.valueOf(flight.getFlightPrice()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButtonViewFlightDetails = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        comboBoxAirliner = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFlightNo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSource = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtAvailableSeats = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDestination = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDepartureTime = new javax.swing.JTextField();
        txtSeats = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtArrivalTime = new javax.swing.JTextField();
        FlightDetailsSaveButton = new javax.swing.JButton();
        UpdateFlightDetailsButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        backButtonViewFlightDetails.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        backButtonViewFlightDetails.setText("<< Back");
        backButtonViewFlightDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonViewFlightDetailsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("View Flight Details");

        comboBoxAirliner.setEnabled(false);
        comboBoxAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxAirlinerActionPerformed(evt);
            }
        });

        jLabel10.setText("Price: ");

        jLabel2.setText("Airliner Name: ");

        jLabel3.setText("Flight Number: ");

        jLabel4.setText("Source: ");

        jLabel9.setText("Available Seats: ");

        jLabel5.setText("Destination: ");

        jLabel7.setText("Departure Time: ");

        jLabel6.setText("Seats: ");

        jLabel8.setText("Arrival Time: ");

        FlightDetailsSaveButton.setText("Save");
        FlightDetailsSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlightDetailsSaveButtonActionPerformed(evt);
            }
        });

        UpdateFlightDetailsButton.setText("Update");
        UpdateFlightDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateFlightDetailsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 222, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(217, 217, 217))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButtonViewFlightDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(comboBoxAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtSource, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtFlightNo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtArrivalTime, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDepartureTime, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(txtAvailableSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(FlightDetailsSaveButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(UpdateFlightDetailsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backButtonViewFlightDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBoxAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFlightNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDepartureTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtArrivalTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAvailableSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FlightDetailsSaveButton)
                    .addComponent(UpdateFlightDetailsButton))
                .addContainerGap(63, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonViewFlightDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonViewFlightDetailsActionPerformed
        // TODO add your handling code here:
        cardSequenceJPanel.remove(this);
        CardLayout layout = (CardLayout)cardSequenceJPanel.getLayout();
        layout.previous(cardSequenceJPanel);
        Component[] comps= cardSequenceJPanel.getComponents();
        for(Component c:comps)
        {
            if(c instanceof ManageAirlinerJPanel)
            {
                ManageAirlinerJPanel panel=(ManageAirlinerJPanel) c;               
                panel.populateAirlinersTable();
            }
        }
    }//GEN-LAST:event_backButtonViewFlightDetailsActionPerformed

    public boolean checkString(String string){
        Pattern p = Pattern.compile("^[A-Za-z]+$");
        Matcher m = p.matcher(string);
        boolean b = m.matches();
        return b;
    }
    
    public boolean checkFlightNumber(String string){
        Pattern p = Pattern.compile("^[\\w]+-[\\w]+$");
        Matcher m = p.matcher(string);
        boolean b = m.matches();
        return b;
    }
    
    public boolean checkTimePattern(String string){
       Pattern p = Pattern.compile("^[0-9]+:[0-9]+$");
       Matcher m = p.matcher(string);
       boolean b = m.matches();
       return b;
    }
    
    private void FlightDetailsSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlightDetailsSaveButtonActionPerformed
        // TODO add your handling code here:
        String flightNumber = txtFlightNo.getText();
        String source = txtSource.getText();
        String destination = txtDestination.getText();
        String departure = txtDepartureTime.getText();
        String arrival = txtArrivalTime.getText();
        try{
            Double price = Double.parseDouble(txtPrice.getText());
            int totalSeats = Integer.parseInt(txtSeats.getText());
            flight.setFlightPrice(price);
            flight.setTotalSeats(totalSeats);
            
        if(!checkFlightNumber(flightNumber)){
            JOptionPane.showMessageDialog(null, "Please enter valid flight number : XX-XXXX");
        }
        else if(!checkTimePattern(departure)){
            JOptionPane.showMessageDialog(null, "Please enter valid departure time : XX:XX");
        }
        else if(!checkTimePattern(arrival)){
            JOptionPane.showMessageDialog(null, "Please enter valid arrival time : XX:XX");
        }
        else if(!checkString(source)){
            JOptionPane.showMessageDialog(null, "Please enter valid source");
        }
        else if(!checkString(destination)){
            JOptionPane.showMessageDialog(null, "Please enter valid destination");
        }
        else {
            flight.setFlightNumber(flightNumber);
            flight.setSource(source);
            flight.setDestination(destination);
            flight.setArrivalTime(arrival);
            flight.setDepartureTime(departure);
            FlightDetailsSaveButton.setEnabled(false);
            UpdateFlightDetailsButton.setEnabled(true);
            txtFlightNo.setEnabled(false);
            txtSource.setEnabled(false);
            txtDestination.setEnabled(false);
            txtDepartureTime.setEnabled(false);
            txtArrivalTime.setEnabled(false);
            txtPrice.setEnabled(false);
            txtSeats.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Fligh details successfully updated");
        }
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Price and Total seats should be a number");
        }
    }//GEN-LAST:event_FlightDetailsSaveButtonActionPerformed

    private void UpdateFlightDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateFlightDetailsButtonActionPerformed
        // TODO add your handling code here:
        txtFlightNo.setEnabled(true);
        txtSource.setEnabled(true);
        txtDestination.setEnabled(true);
        txtDepartureTime.setEnabled(true);
        txtArrivalTime.setEnabled(true);
        txtPrice.setEnabled(true);
        txtSeats.setEnabled(true);
        UpdateFlightDetailsButton.setEnabled(false);
        FlightDetailsSaveButton.setEnabled(true);
    }//GEN-LAST:event_UpdateFlightDetailsButtonActionPerformed

    private void comboBoxAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxAirlinerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxAirlinerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FlightDetailsSaveButton;
    private javax.swing.JButton UpdateFlightDetailsButton;
    private javax.swing.JButton backButtonViewFlightDetails;
    private javax.swing.JComboBox<String> comboBoxAirliner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtArrivalTime;
    private javax.swing.JTextField txtAvailableSeats;
    private javax.swing.JTextField txtDepartureTime;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtFlightNo;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtSeats;
    private javax.swing.JTextField txtSource;
    // End of variables declaration//GEN-END:variables
}
