/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DrugSupplier;

import Business.Chemical.Chemical;
import Business.Drug.Drug;
import Business.Drug.DrugList;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Gene.Gene;
import Business.Network.Network;
import Business.Organization.DrugOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author keshav
 */
public class AddChemicalsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form addChemicalsJPanel
     */
    private Drug drug;
    private DrugList drugList;
    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private DrugOrganization drugOrganization ;
    private Enterprise enterprise;
    private Object e;
    private Network network;
    public AddChemicalsJPanel(JPanel userProcessContainer,EcoSystem business,UserAccount userAccount,DrugOrganization organization,Enterprise enterprise,Network network,Drug drug) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.business = business;
        this.enterprise = enterprise;
        this.network = network;
        this.drug = drug;
        this.drugOrganization = (DrugOrganization)organization;
        populateTable();
    }

    public void populateTable(){
         DefaultTableModel model = (DefaultTableModel)tblChemicalGene.getModel();
        
        model.setRowCount(0);
        Object[] row = new Object[2];
        int i = 0;
            for(Chemical c : drug.getChemicalList().getChemicalList()){
                 
                 row[0] = c.getChemicalName();
                 
                    
                    Gene g=  drug.getGeneHistory().getGeneList().get(i);
                      
                      row[1] = g.getGeneName();
                      model.addRow(row);
                     i++;
                     }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGeneandChemical = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChemicalGene = new javax.swing.JTable();
        lblChemical = new javax.swing.JLabel();
        lblGene = new javax.swing.JLabel();
        txtChemical = new javax.swing.JTextField();
        txtGene = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();

        lblGeneandChemical.setFont(new java.awt.Font("Wide Latin", 3, 24)); // NOI18N
        lblGeneandChemical.setText("Gene and Chemical Names");

        tblChemicalGene.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 20)); // NOI18N
        tblChemicalGene.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ChemicalName", "GeneName"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblChemicalGene.setRowHeight(30);
        tblChemicalGene.getTableHeader().setResizingAllowed(false);
        tblChemicalGene.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblChemicalGene);

        lblChemical.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lblChemical.setText("Chemical Name :");

        lblGene.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lblGene.setText("Gene Name :");

        btnBack.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(51, 0, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(51, 0, 255));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(191, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(btnBack)
                        .addGap(245, 245, 245)
                        .addComponent(btnAdd))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(lblGeneandChemical))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(271, 271, 271)
                                .addComponent(lblGene, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblChemical)
                                .addGap(47, 47, 47)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtGene)
                            .addComponent(txtChemical, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(lblGeneandChemical)
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChemical)
                    .addComponent(txtChemical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGene)
                    .addComponent(txtGene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnAdd))
                .addContainerGap(193, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        AddDrugJPanel dwjp = (AddDrugJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);   
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
         String chemicalName = txtChemical.getText().trim();
         String geneName = txtGene.getText().trim();
         if(chemicalName.isEmpty())
         {
             JOptionPane.showMessageDialog(null,"Please enter the chemical name");
             return;
         }
         if(geneName.isEmpty())
         {
             JOptionPane.showMessageDialog(null, "please enter the gene name ");
             return;
         }
         ArrayList<String> chemicalCheck = new ArrayList<>();
         for(Chemical c : drug.getChemicalList().getChemicalList())
         {
             chemicalCheck.add(c.getChemicalName().toLowerCase());
             
         }
         ArrayList<String>genecheck= new ArrayList<>();
         for(Gene g:drug.getGeneHistory().getGeneList())
         {
             genecheck.add(g.getGeneName().toLowerCase());
         }
         if(chemicalCheck.contains(chemicalName.toLowerCase()))
         {
             JOptionPane.showMessageDialog(null,"Chemical already exists in the drug ");
             return;
             
         }
         if(genecheck.contains(geneName.toLowerCase()))
         {
          JOptionPane.showMessageDialog(null,"Gene already exists in the drug ");
             return;   
         }
        drug.getChemicalList().addChemicalList().setChemicalName(chemicalName);
        drug.getGeneHistory().addGene().setGeneName(geneName);
       
        populateTable();        
        txtChemical.setText("");
        txtGene.setText("");
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblChemical;
    private javax.swing.JLabel lblGene;
    private javax.swing.JLabel lblGeneandChemical;
    private javax.swing.JTable tblChemicalGene;
    private javax.swing.JTextField txtChemical;
    private javax.swing.JTextField txtGene;
    // End of variables declaration//GEN-END:variables
}
